### ISSUE TITLE
Error importing dataset

### ISSUE THREAD

**Issue by esebastian** [civio/onodo#309]
An exception is raised when in the 'Nodes' sheet there is a column with data but no header value

**Comment by esebastian** [comment]
The callback trace of the exception is:
```
NoMethodError (undefined method `downcase' for nil:NilClass):
  app/services/xlsx_dataset_importer.rb:128:in `block in create_nodes'
  app/services/xlsx_dataset_importer.rb:128:in `map'
  app/services/xlsx_dataset_importer.rb:128:in `create_nodes'
  app/services/xlsx_dataset_importer.rb:26:in `import'
  app/controllers/visualizations_controller.rb:31:in `create'
```
